/**
 * This file is generated by jsonrpcstub, DO NOT CHANGE IT MANUALLY!
 */

#ifndef JSONRPC_CPP_STUB_ROVERCLIENT_H_
#define JSONRPC_CPP_STUB_ROVERCLIENT_H_

#include <jsonrpccpp/client.h>

class RoverClient : public jsonrpc::Client
{
    public:
        RoverClient(jsonrpc::IClientConnector &conn, jsonrpc::clientVersion_t type = jsonrpc::JSONRPC_CLIENT_V2) : jsonrpc::Client(conn, type) {}

        int setJointAngle(int joint, double angle) throw (jsonrpc::JsonRpcException)
        {
            Json::Value p;
            p["angle"] = angle;
            p["joint"] = joint;
            Json::Value result = this->CallMethod("setJointAngle",p);
            if (result.isInt())
                return result.asInt();
            else
                throw jsonrpc::JsonRpcException(jsonrpc::Errors::ERROR_CLIENT_INVALID_RESPONSE, result.toStyledString());
        }
        double getJointAngle(int joint) throw (jsonrpc::JsonRpcException)
        {
            Json::Value p;
            p["joint"] = joint;
            Json::Value result = this->CallMethod("getJointAngle",p);
            if (result.isDouble())
                return result.asDouble();
            else
                throw jsonrpc::JsonRpcException(jsonrpc::Errors::ERROR_CLIENT_INVALID_RESPONSE, result.toStyledString());
        }
        int setJointSpeed(int joint, int speed) throw (jsonrpc::JsonRpcException)
        {
            Json::Value p;
            p["joint"] = joint;
            p["speed"] = speed;
            Json::Value result = this->CallMethod("setJointSpeed",p);
            if (result.isInt())
                return result.asInt();
            else
                throw jsonrpc::JsonRpcException(jsonrpc::Errors::ERROR_CLIENT_INVALID_RESPONSE, result.toStyledString());
        }
        int getJointSpeed(int joint) throw (jsonrpc::JsonRpcException)
        {
            Json::Value p;
            p["joint"] = joint;
            Json::Value result = this->CallMethod("getJointSpeed",p);
            if (result.isInt())
                return result.asInt();
            else
                throw jsonrpc::JsonRpcException(jsonrpc::Errors::ERROR_CLIENT_INVALID_RESPONSE, result.toStyledString());
        }
        int setCartesianPosition(double x, double y, double z) throw (jsonrpc::JsonRpcException)
        {
            Json::Value p;
            p["x"] = x;
            p["y"] = y;
            p["z"] = z;
            Json::Value result = this->CallMethod("setCartesianPosition",p);
            if (result.isInt())
                return result.asInt();
            else
                throw jsonrpc::JsonRpcException(jsonrpc::Errors::ERROR_CLIENT_INVALID_RESPONSE, result.toStyledString());
        }
        Json::Value getCartesianPosition() throw (jsonrpc::JsonRpcException)
        {
            Json::Value p;
            p = Json::nullValue;
            Json::Value result = this->CallMethod("getCartesianPosition",p);
            if (result.isArray())
                return result;
            else
                throw jsonrpc::JsonRpcException(jsonrpc::Errors::ERROR_CLIENT_INVALID_RESPONSE, result.toStyledString());
        }
        int setGripper(bool open) throw (jsonrpc::JsonRpcException)
        {
            Json::Value p;
            p["open"] = open;
            Json::Value result = this->CallMethod("setGripper",p);
            if (result.isInt())
                return result.asInt();
            else
                throw jsonrpc::JsonRpcException(jsonrpc::Errors::ERROR_CLIENT_INVALID_RESPONSE, result.toStyledString());
        }
        int setWheelSpeed(int wheel, int speed) throw (jsonrpc::JsonRpcException)
        {
            Json::Value p;
            p["speed"] = speed;
            p["wheel"] = wheel;
            Json::Value result = this->CallMethod("setWheelSpeed",p);
            if (result.isInt())
                return result.asInt();
            else
                throw jsonrpc::JsonRpcException(jsonrpc::Errors::ERROR_CLIENT_INVALID_RESPONSE, result.toStyledString());
        }
        int getWheelSpeed(int wheel) throw (jsonrpc::JsonRpcException)
        {
            Json::Value p;
            p["wheel"] = wheel;
            Json::Value result = this->CallMethod("getWheelSpeed",p);
            if (result.isInt())
                return result.asInt();
            else
                throw jsonrpc::JsonRpcException(jsonrpc::Errors::ERROR_CLIENT_INVALID_RESPONSE, result.toStyledString());
        }
	Json::Value getGPS() throw (jsonrpc::JsonRpcException)
        {
            Json::Value p;
            p = Json::nullValue;
            Json::Value result = this->CallMethod("getGPS",p);
            if (result.isArray())
                return result;
            else
                throw jsonrpc::JsonRpcException(jsonrpc::Errors::ERROR_CLIENT_INVALID_RESPONSE, result.toStyledString());
        }
};

#endif //JSONRPC_CPP_STUB_ROVERCLIENT_H_
